version: '3.4'

services:
  deviceDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 2astazeY
      MSSQL_DB: dev
      MSSQL_USER: ryan
      MSSQL_PASSWORD: ITSAMEMARIO
    ports:
      - "1434:1433"
    container_name: deviceDb
    
  orgDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 2astazeY
      MSSQL_DB: dev
      MSSQL_USER: ryan
      MSSQL_PASSWORD: ITSAMEMARIO
    ports:
      - "1435:1433"
    container_name: orgDb  
    
  authDb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 2astazeY
      MSSQL_DB: dev
      MSSQL_USER: ryan
      MSSQL_PASSWORD: ITSAMEMARIO
    ports:
      - "1436:1433"
    container_name: authDb
  
#  DeviceManagement.API:
#    environment:
#      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+:443;http://+:80
#    ports:
#      - "80"
#      - "443"
#    volumes:
#      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro